---
title: Artist Project Group
author: Artist Project Group
email: info@artistprojectgroup.com
description: Founded in Vienna, Austria, 2015
baseurl: ''
url: artistprojectgroup.com
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
